prompt = '~  '
padding = 185
fonts = ['IBM Plex Mono']
font_size = 18.0

[history]
decrease_interval = 24

[colors]
background = '#070707bb'
prompt = '#abb2bfff'
text = '#ffffffff'
text_query = '#00ffffff'
text_selected = '#ff0000ff'

[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
