#!/usr/local/bin/perl

use strict;
use warnings;

my $acpi = `acpiconf -i 0 2> /dev/null`;
my ($source, $time, $message, $stat, $charge);

if ($acpi =~ /Remaining capacity:\s+(\d+)/) {
    $charge = $1;
    $source = "battery";
    $time = ($acpi =~ /Remaining time:\s+(.*)/) ? $1 : "unknown";

    if ($charge == 100) {
        $message = "charged";
    } elsif ($charge <= 15) {
        $message = "critical";
    }

    if ($time eq "unknown") {
        $stat = "ac";
        $time = "$charge% charged";
    }

} else {
    $source = "psu";
    $time = "PSU";
}

print '{"source":"' . $source . '","time":"' . $time . '","stat":"'
    . (defined $stat ? $stat : '') . '","message":"'
    . (defined $message ? $message : '') . '","percentage":'
    . (defined $charge ? $charge : '') . '}' . "\n";
