#!/usr/local/bin/perl
use strict;
use warnings;

my $mixer = `mixer`;
my ($vol, $pcm, $rec, $mic, $igain, $ogain) = ([], [], [], [], [], []);

while ($mixer =~ /(\w+)\s*=\s*([\d\.]+):([\d\.]+)/g) {
    my $type = $1;
    my $value = [$2, $3];

    $value->[0] *= 100;
    $value->[1] *= 100;

    if ($type eq 'vol') {
        $vol = $value;
    } elsif ($type eq 'pcm') {
        $pcm = $value;
    } elsif ($type eq 'rec') {
        $rec = $value;
    } elsif ($type eq 'mic') {
        $mic = $value;
    } elsif ($type eq 'igain') {
        $igain = $value;
    } elsif ($type eq 'ogain') {
        $ogain = $value;
    }
}

my $output = '{';
my @fields = ('vol', 'pcm', 'rec', 'mic', 'igain', 'ogain');
my @values = ($vol, $pcm, $rec, $mic, $igain, $ogain);

for (my $i = 0; $i < @fields; $i++) {
    my $field = $fields[$i];
    my $value = $values[$i];

    if (scalar(@$value) == 2) {
        $output .= "\"$field\":[$value->[0],$value->[1]],";
    }
}

$output =~ s/,$//;
$output .= "}";

print $output;
