#!/usr/local/bin/perl

use strict;
use warnings;

my $apm = `apm`;
my ($source, $time, $message, $charge, $label, $online);

for my $line (split /\n/, $apm) {
    if ($line =~ /^AC Line status:\s*(on-line)/i) {
        if ($1 eq "on-line") { $online = 1; }
    }
    if ($line =~ /^Battery status:\s*(charging)/i) {
        if ($1 eq "charging") { $message = "batt-charging"; }
    }
    if ($line =~ /^Number of batteries:\s*(\d+)/i) {
        if ($1 != 0) { $source = "battery"; }
    }
    if ($line =~ /^Remaining battery life:\s*(\d+)%/) { $charge = $1; }
    if ($line =~ /^Remaining battery time:\s*(\S+)/) { $time = $1; }
}

if ($charge == 100) {
    $message = "batt-charged";
    $label = ($online ? "󰂅" : "󰁹");
} elsif ($charge >= 90) {
    $message = "batt-charged";
    $label = ($online ? "󰂋" : "󰂂");
} elsif ($charge >= 80) {
    $message = "batt-charged";
    $label = ($online ? "󰂊" : "󰂁");
} elsif ($charge >= 70) {
    $label = ($online ? "󰢞" : "󰂀");
} elsif ($charge >= 60) {
    $label = ($online ? "󰂉" : "󰁿");
} elsif ($charge >= 50) {
    $label = ($online ? "󰢝" : "󰁾");
} elsif ($charge >= 40) {
    $label = ($online ? "󰂈" : "󰁽");
} elsif ($charge > 30) {
     $message = "batt-critical";
     $label = ($online ? "󰂇" : "󰁼");
} elsif ($charge < 30) {
    $message = "batt-critical";

    if ($charge >= 20) {
        $label = ($online ? "󰂆" : "󰁻");
    } else {
        $label = ($online ? "󰢜" : "󰁺");
    }

    if ($time ne "unknown") {
        system("notify-send",
               "-u",
               "critical",
               "--icon", "battery-caution-symbolic",
               "-t", "45000",
               "Battery" . " level",
               $charge . "%"
            );
    }
}

if ($time eq "unknown") { $time = "$charge% charged"; }

print
    '{"source":"' . $source .
    '","time":"' . $time .
    '","label":"' . (defined $label ? $label : '󰄌') .
    '","message":"' . (defined $message ? $message : '') .
    '"}';
