#!/bin/sh

ARG=$1

case "$ARG" in
true)
	doas service bluetooth stop ubt0
	notify-send "Bluetooth deactivated" --icon=bluetooth-disabled-symbolic
	;;
false)
	doas service bluetooth start ubt0
	notify-send "Bluetooth activated" --icon=bluetooth-active-symbolic
	;;
esac
