---
window:
  padding:
    x: 10
    y: 7

  dynamic_padding: false
  opacity: 0.7

font:
  normal:
    family: monospace

  size: 11.0

colors:
  primary:
    background: '#000000'
    foreground: '#f8f8f8'

  normal:
    black: '#1d1f21'
    red: '#d62a30'
    green: '#4ce70e'
    yellow: '#f0f221'
    blue: '#1257ea'
    magenta: '#c316f6'
    cyan: '#00f2d2'
    white: '#c5c8c6'

  transparent_background_colors: true

cursor:
  style:
    shape: block
    blinking: on

  blink_interval: 600
  unfocused_hollow: true
