source=./bind.conf
source=./fx.conf

exec-once=sh ~/bin/desktop-startup

cursor_size=20
border_radius=8
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0

scroller_structs=20
scroller_default_proportion=0.8
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

new_is_master=0
default_mfact=0.55
default_nmaster=1
smartgaps=0

hotarea_size=10
enable_hotarea=1
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
cursor_size=24
drag_tile_to_tile=1

repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us

disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1

mouse_natural_scrolling=1

gappih=6
gappiv=6
gappoh=8
gappov=8
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=0
rootcolor=0x201b14ff
bordercolor=0x444444ff
focuscolor=0xc9b890ff
maximizescreencolor=0x89aa61ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

layerrule=layer_name:quickshell,noblur:0,noshadow:0

tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile
