source = ./env.conf
source = ./layouts.conf
source = ./geometry.conf
source = ./control.conf
source = ./colors.conf
source = ./fx.conf
source = ./rules.conf
source = ./bind.conf

exec-once = sh ~/bin/desktop-startup

focused_opacity = 1.0
unfocused_opacity = 1.0
