focused_opacity = 1.0
unfocused_opacity = 1.0

blur = 1
blur_layer = 1
blur_optimized = 1
blur_params_num_passes = 2
blur_params_radius = 5
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.0

shadows = 0
layer_shadows = 1
shadow_only_floating = 0
shadows_size = 10
shadows_blur = 15
shadows_position_x = 0
shadows_position_y = 0

animations = 1
layer_animations = 1
animation_type_open = slide
animation_type_close = slide
animation_fade_in = 1
animation_fade_out = 1
tag_animation_direction = 1
zoom_initial_ratio = 0.3
zoom_end_ratio = 0.8
fadein_begin_opacity = 0.5
fadeout_begin_opacity = 0.8
animation_duration_move = 300
animation_duration_open = 300
animation_duration_tag = 300
animation_duration_close = 300
animation_duration_focus = 0
animation_curve_open = 0.46,1.0,0.29,1
animation_curve_move = 0.46,1.0,0.29,1
animation_curve_tag = 0.46,1.0,0.29,1
animation_curve_close = 0.08,0.92,0,1
animation_curve_focus = 0.46,1.0,0.29,1
animation_curve_opafadeout = 0.5,0.5,0.5,0.5
animation_curve_opafadein = 0.46,1.0,0.29,1
