scroller_structs = 20
scroller_default_proportion = 0.8
scroller_focus_center = 0
scroller_prefer_center = 0
edge_scroller_pointer_focus = 1
scroller_default_proportion_single = 1.0
scroller_proportion_preset = 0.5,0.8,1.0

new_is_master = 0
default_mfact = 0.55
default_nmaster = 1
hotarea_size = 10
enable_hotarea = 1
ov_tab_mode = 0
overviewgappi = 5
overviewgappo = 30

axis_bind_apply_timeout = 100
focus_on_activate = 1
sloppyfocus = 1
focus_cross_monitor = 0
focus_cross_tag = 0
enable_floating_snap = 0
snap_distance = 30
drag_tile_to_tile = 1

scratchpad_width_ratio = 0.8
scratchpad_height_ratio = 0.9
