layerrule=layer_name:quickshell,noblur:0,noshadow:0

windowrule=tags:1,appid:Signal
windowrule=tags:2,appid:foot
windowrule=tags:2,appid:Alacritty
windowrule=tags:2,appid:com.mitchellh.ghostty
windowrule=tags:3,appid:firefox
windowrule=tags:4,appid:emacs
windowrule=tags:4,appid:ev.zed.Zed
windowrule=tags:5,appid:gedit
windowrule=tags:6,appid:thunar
windowrule=tags:7,appid:Claws-mail
windowrule=tags:8,appid:blender
windowrule=tags:8,appid:mpv
windowrule=tags:8,appid:vlc
windowrule=tags:9,appid:org.nicotine_plus.Nicotine

tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile
