---
"on":
  push:
  pull_request:

name: ShellCheck
permissions: {}

jobs:
  shellcheck:
    runs-on: codeberg-small
    strategy:
      matrix:
        shell:
          - sh
          - bash
          - dash
          - ksh

    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run ShellCheck
        uses: https://github.com/ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: "-s ${{ matrix.shell }}"
        with:
          ignore_names: .zshrc
