theme = 'catppuccin'
footer_panel_list = ['processes', 'metadata', 'clipboard']
auto_check_update = false
transparent_background = false

border_top = '━'
border_bottom = '━'
border_left = '┃'
border_right = '┃'
border_top_left = '┏'
border_top_right = '┓'
border_bottom_left = '┗'
border_bottom_right = '┛'
border_middle_left = '┣'
border_middle_right = '┫'

metadata = false
