confirm = ['enter', 'l']
quit = ['q', 'esc']
list_up = ['up', 'k']
list_down = ['down', 'j']
close_file_panel = ['w', '']
create_new_file_panel = ['n', '']
next_file_panel = ['tab', 'L']
previous_file_panel = ['shift+left', 'H']
toggle_file_preview_panel = ['f', '']
focus_on_process_bar = ['p', '']
focus_on_sidebar = ['s', '']
focus_on_metadata = ['m', '']
file_panel_item_create = ['ctrl+n', '']
file_panel_item_rename = ['ctrl+r', '']
copy_items = ['ctrl+c', '']
paste_items = ['ctrl+v', '']
cut_items = ['ctrl+x', '']
delete_items = ['ctrl+d', 'delete']
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
pinned_directory = ['P', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v', '']
open_help_menu = ['?', '']
confirm_typing = ['enter', '']
cancel_typing = ['ctrl+c', 'esc']
parent_directory = ['h', 'backspace']
search_bar = ['/', '']
file_panel_select_mode_items_select_down = ['shift+down', 'J']
file_panel_select_mode_items_select_up = ['shift+up', 'K']
file_panel_select_all_items = ['A', '']
