---
targets:
  - https://github.com/charlesrocket/adventofcode
  - https://github.com/charlesrocket/ansible-containers
  - https://github.com/charlesrocket/dotfiles
  - https://github.com/charlesrocket/skully
  - https://github.com/charlesrocket/beastie
  - https://github.com/charlesrocket/pixelmosh
  - https://github.com/charlesrocket/webpixels
  - https://github.com/charlesrocket/hell
  - https://github.com/charlesrocket/dorst
  - https://github.com/charlesrocket/dotfiles_role
  - https://github.com/charlesrocket/git_role
  - https://github.com/charlesrocket/openbsd-station
  - https://github.com/charlesrocket/freebsd-station
  - https://github.com/charlesrocket/freebsd-server
  - https://github.com/charlesrocket/debian-server
  - https://github.com/charlesrocket/macos-station
  - https://github.com/charlesrocket/htb-files
  - https://github.com/charlesrocket/misc-files
