-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

local mod = "SUPER"

hl.layer_rule({
    match = { namespace = "match:namespace notifications" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "match:namespace quickshell" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "match:namespace eww-bar" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "match:namespace rofi" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "match:namespace logout_dialog" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "match:namespace quickshell" },
    ignore_alpha = 0,
})

hl.window_rule({
    match = {
        class = "^(.*)$",
    },
    no_blur = false,
})

hl.window_rule({
    match = {
        class = "com.mitchellh.ghostty",
    },
    no_blur = false,
})

hl.window_rule({
    match = {
        class = "Alacritty",
    },
    no_blur = false,
})

hl.window_rule({
    match = {
        class = "foot",
    },
    no_blur = false,
})

hl.window_rule({
    match = {
        class = "dev.zed.Zed",
    },
    no_blur = false,
})

hl.window_rule({
    match = {
        class = "ghidra-Ghidra",
    },
    maximize = true,
})

hl.window_rule({
    match = {
        class = "Signal",
    },
    workspace = "1",
})

hl.window_rule({
    match = {
        class = "com.mitchellh.ghostty",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        class = "Alacritty",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        class = "foot",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        class = "firefox",
    },
    workspace = "3",
})

hl.window_rule({
    match = {
        class = "emacs",
    },
    workspace = "4",
})

hl.window_rule({
    match = {
        class = "dev.zed.Zed",
    },
    workspace = "4",
})

hl.window_rule({
    match = {
        class = "gedit",
    },
    workspace = "5",
})

hl.window_rule({
    match = {
        class = "thunar",
    },
    workspace = "6",
})

hl.window_rule({
    match = {
        class = "Claws-mail",
    },
    workspace = "7",
})

hl.window_rule({
    match = {
        class = "blender",
    },
    workspace = "8",
})

hl.window_rule({
    match = {
        class = "vlc",
    },
    workspace = "8",
})

hl.window_rule({
    match = {
        class = "mpv",
    },
    workspace = "8",
})

hl.window_rule({
    match = {
        class = "org.nicotine_plus.Nicotine",
    },
    workspace = "9",
})

hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("foot"))
hl.bind(mod .. " + F2", hl.dsp.exec_cmd("foot"))
hl.bind(mod .. " + F3", hl.dsp.exec_cmd("firefox"))
hl.bind(mod .. " + F4", hl.dsp.exec_cmd("zedit"))
hl.bind(mod .. " + F5", hl.dsp.exec_cmd("gedit"))
hl.bind(mod .. " + F6", hl.dsp.exec_cmd("thunar"))
hl.bind(mod .. " + F7", hl.dsp.exec_cmd("claws-mail"))
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + K", hl.dsp.exec_cmd("hyprctl reload,"))
hl.bind(mod .. " + R", hl.dsp.exec_cmd("quickshell -c topbar ipc call main logout"))
hl.bind(mod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + D", hl.dsp.exec_cmd("quickshell -c topbar ipc call main launcher"))
hl.bind(mod .. " + P", hl.dsp.window.pseudo())

hl.bind(mod .. " + CTRL + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + CTRL + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + CTRL + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + CTRL + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mod .. " + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + left", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mod .. " + M", hl.dsp.submap("resize"))

hl.define_submap("resize", function()

    hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("backlight +"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("backlight -"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("quickshell ipc call audio volumeUp"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("quickshell ipc call audio volumeDown"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("quickshell ipc call audio toggleMute"))

hl.permission({ binary = "*", type = "screencopy", mode = "ask" })
hl.permission({ binary = "*", type = "keyboard", mode = "ask" })
hl.permission({ binary = "*", type = "plugin", mode = "ask" })

hl.permission({ binary = "/usr/local/bin/hyprlock", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/local/bin/grim", type = "screencopy", mode = "allow" })
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 1,
        col = {
            active_border = "rgba(4e4e4eaa)",
            inactive_border = "rgba(4e4e4eaa)",
        },
        layout = "dwindle",
    },
    decoration = {
        rounding = 8,
        dim_inactive = false,
        dim_strength = 0.1,
        shadow = {
            enabled = false,
            range = 6,
            render_power = 5,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 2,
            passes = 3,
            ignore_opacity = true,
            new_optimizations = true,
        },
    },
    animations = {
        enabled = true,
    },
    dwindle = {
        force_split = 2,
        preserve_split = false,
    },
    input = {
        kb_layout = "us,no",
        kb_options = "grp:alt_shift_toggle",
        sensitivity = 0,
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
        },
    },
    cursor = {
        inactive_timeout = 5,
    },
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
        enforce_permissions = true,
    },
    misc = {
        disable_autoreload = true,
        disable_hyprland_logo = true,
    },
    xwayland = {
        enabled = true,
        use_nearest_neighbor = true,
        force_zero_scaling = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor Bibata-Original-Classic 20")
    hl.exec_cmd("~/bin/desktop-startup")
end)
