language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install pip --upgrade"
  - "pip install -r tests-requirements.txt"
  - "pip install -r requirements.txt"
script:
  ./tests.sh
after_success:
  coveralls
