config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
profiles:
  rkt-mbp.local:
    dotfiles:
    - f_vimrc
