add_newline = false
format = '$character$directory$git_branch$pijul_channel '
right_format = '$all'

[character]
success_symbol = '[ ](bold red)'

[directory]
truncate_to_repo = true
truncation_length = 1
read_only = ' 󰌾'

[line_break]
disabled = true

[time]
disabled = true

[battery]
disabled = true

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '
disabled = true

[status]
disabled = true
symbol = 'X'
map_symbol = true
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '

[pijul_channel]
disabled = false
format = '[\($channel\)](bold blue)'

[git_branch]
disabled = false
format = '[\($branch\)](bold blue)'

[git_commit]
disabled = true
only_detached = false
tag_disabled = false
tag_symbol = '  '
style = 'bright-black'
format = '[$hash$tag]($style) '

[git_state]
disabled = false

[git_status]
disabled = false
format = '$all_status$ahead_behind'
ahead = '󰧇 '
behind = '󰦿 '
conflicted = '[](bright-red) '
diverged = '[](purple) '
staged = '[](green) '
modified = '[](yellow) '
deleted = '[](red) '
renamed = '[](blue) '
untracked = '[](cyan) '
stashed = '󰆓 '
up_to_date = ''

[git_metrics]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true
