add_newline = false
format = '$character$directory$git_branch$pijul_channel$fossil_branch$hg_branch '
right_format = '$all'

[character]
success_symbol = '[](bold red) '
error_symbol = '[](bold red) '

[directory]
truncate_to_repo = true
truncation_length = 1
truncation_symbol = ''
read_only = ' 󰌾'
read_only_style = 'red'
home_symbol = '󰆧'

[line_break]
disabled = true

[time]
disabled = true

[memory_usage]
disabled = true

[os]
disabled = true

[netns]
disabled = true

[shlvl]
disabled = true

[cmd_duration]
disabled = true
show_milliseconds = true
min_time = 0
style = 'bright-black'
format = '[$duration]($style) '

[battery]
disabled = true

[localip]
disabled = true
ssh_only = true
format = '@[$localipv4](bold red) '

[username]
disabled = true
show_always = true
style_user = 'bold green'
style_root = 'bold red'
format = ' [$user]($style) '

[sudo]
disabled = false
format = '[$symbol]($style) '
style = 'bold green'
symbol = ''

[status]
disabled = true
symbol = 'X'
map_symbol = true
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '

[buf]
disabled = true

[bun]
disabled = true

[direnv]
disabled = true

[package]
disabled = false
format = '[pkg](italic) [$symbol$version]($style) '
symbol = '󰏗 '
version_format = '${raw}'

[fossil_metrics]
disabled = true

[fossil_branch]
disabled = false
format = '[\($branch\)](bold blue)'

[hg_branch]
disabled = false
format = '[\($branch\)](bold blue)'

[pijul_channel]
disabled = false
format = '[\($channel\)](bold blue)'

[git_branch]
disabled = false
format = '[\($branch\)](bold blue)'

[git_commit]
disabled = false
commit_hash_length = 7
only_detached = true
tag_disabled = true
tag_symbol = '  '
style = 'bright-black'
format = '[$hash$tag]($style) '

[git_state]
disabled = false

[git_status]
disabled = false
format = '$all_status$ahead_behind'
ahead = '󰧇 '
behind = '󰦿 '
conflicted = '[](bright-red) '
diverged = '[](purple) '
staged = '[](green) '
modified = '[](yellow) '
deleted = '[](red) '
renamed = '[](blue) '
untracked = '[](cyan) '
stashed = '󰆓 '
up_to_date = ''

[git_metrics]
disabled = true

[nix_shell]
disabled = true

[guix_shell]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[azure]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true
