Net/ThemeName "Pop-dark"
Net/IconThemeName "Pop"
Gtk/CursorThemeName "Bibata-Original-Classic"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 1
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
