---

'on':
  push:
  pull_request:

name: Linter
permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell:
          - sh
          - bash
          - dash
          - ksh

    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: '-s ${{ matrix.shell }}'
        with:
          ignore_names: .zshrc

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          FILTER_REGEX_EXCLUDE: .*README\.md*

  lint-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint and fix
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_SHELL_SHFMT: true
          FIX_YAML_PRETTIER: true
          FIX_CSS_PRETTIER: true

      - name: Push linting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
