---

'on':
  push:
  pull_request:

name: Linter
permissions: read-all

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell:
          - sh
          - bash
          - dash
          - ksh

    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: '-s ${{ matrix.shell }}'
        with:
          ignore_names: .zshrc

  lint:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Lint
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_SHELL_SHFMT: true
          FIX_YAML_PRETTIER: true
          FIX_CSS_PRETTIER: true
          FIX_CSS: true
          FIX_JSON_PRETTIER: true
          FIX_JSON: true
          FILTER_REGEX_EXCLUDE: .*README\.md*|.*wlogout\/style\.css*|.*eww\.scss*

      - name: Push linting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
