on:
  push:
  pull_request:

name: "Linter"

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell:
          - sh
          - bash
          - dash
          - ksh

    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s ${{ matrix.shell }}
        with:
          ignore_names: .profile .zshrc
