---

"on":
  push:
  pull_request:

name: "Linter"

permissions: read-all

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell:
          - sh
          - bash
          - dash
          - ksh

    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s ${{ matrix.shell }}
        with:
          ignore_names: .zshrc

  superlinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint dotfiles
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: false
          VALIDATE_CSS: false
          FILTER_REGEX_EXCLUDE: .*README\.md*
